// AUTO-GENERATED — do not edit. Regenerated by scripts/generate-configs-index.mjs
import type { AdConfig } from "./types";
import cfg_altenhofen from "../../configs/altenhofen.json";
import cfg_c_sozial from "../../configs/c-sozial.json";
import cfg_esthers_2 from "../../configs/esthers-2.json";
import cfg_fatidienstleistungen from "../../configs/fatidienstleistungen.json";
import cfg_grub from "../../configs/grub.json";
import cfg_horizontal_2 from "../../configs/horizontal-2.json";
import cfg_horizontal_3 from "../../configs/horizontal-3.json";
import cfg_horizontal_4 from "../../configs/horizontal-4.json";
import cfg_horizontal_5 from "../../configs/horizontal-5.json";
import cfg_horizontal from "../../configs/horizontal.json";
import cfg_ihre_praxis from "../../configs/ihre-praxis.json";
import cfg_immoconsult from "../../configs/immoconsult.json";
import cfg_kamine from "../../configs/kamine.json";
import cfg_kuhn from "../../configs/kuhn.json";
import cfg_malerbetrieb from "../../configs/malerbetrieb.json";
import cfg_mehr_als_heizung_2 from "../../configs/mehr-als-heizung-2.json";
import cfg_mehr_als_heizung from "../../configs/mehr-als-heizung.json";
import cfg_meralux from "../../configs/meralux.json";
import cfg_neuhaeuser from "../../configs/neuhaeuser.json";
import cfg_sb_bagger from "../../configs/sb-bagger.json";
import cfg_schuster from "../../configs/schuster.json";
import cfg_wohnbau from "../../configs/wohnbau.json";

export const adConfigs: AdConfig[] = [cfg_altenhofen, cfg_c_sozial, cfg_esthers_2, cfg_fatidienstleistungen, cfg_grub, cfg_horizontal_2, cfg_horizontal_3, cfg_horizontal_4, cfg_horizontal_5, cfg_horizontal, cfg_ihre_praxis, cfg_immoconsult, cfg_kamine, cfg_kuhn, cfg_malerbetrieb, cfg_mehr_als_heizung_2, cfg_mehr_als_heizung, cfg_meralux, cfg_neuhaeuser, cfg_sb_bagger, cfg_schuster, cfg_wohnbau] as AdConfig[];
