// AUTO-GENERATED — do not edit. Regenerated by scripts/generate-configs-index.mjs
import type { AdConfig } from "./types";
import cfg_altenhofen from "../../configs/altenhofen.json";
import cfg_grub from "../../configs/grub.json";
import cfg_immoconsult from "../../configs/immoconsult.json";
import cfg_kamine from "../../configs/kamine.json";
import cfg_kuhn from "../../configs/kuhn.json";
import cfg_malerbetrieb from "../../configs/malerbetrieb.json";
import cfg_meralux from "../../configs/meralux.json";
import cfg_neuhaeuser from "../../configs/neuhaeuser.json";
import cfg_sb_bagger from "../../configs/sb-bagger.json";
import cfg_schuster from "../../configs/schuster.json";
import cfg_wohnbau from "../../configs/wohnbau.json";

export const adConfigs: AdConfig[] = [cfg_altenhofen, cfg_grub, cfg_immoconsult, cfg_kamine, cfg_kuhn, cfg_malerbetrieb, cfg_meralux, cfg_neuhaeuser, cfg_sb_bagger, cfg_schuster, cfg_wohnbau] as AdConfig[];
